# Generated by Django 3.2.13 on 2022-05-12 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_users', '0002_auto_20220512_1625'),
        ('dersler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sorumlu_ogrenciler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dersler.dersler')),
                ('ogr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_users.ogrenci')),
            ],
        ),
    ]
